apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: snow-devhub
  title: Service Now dev hub
  description: Create a record in ServiceNow table
  tags:
    - snow
spec:
  owner: rhdh
  type: service

  parameters:
    - title: Provide Name Entry for snow table
      required:
        - snowName
      properties:
        snowName:
          title: Entry Name Table 1
          type: string
  steps:
    - id: snowCreate
      name: Snow
      action: servicenow:now:table:createRecord
      input:
        tableName: u_rhdhsnowrhdhsnow
        requestBody: {
             u_namename: "${{ parameters.snowName }}"
         }

  output:
    text:
    - title: More information
      content: |
        **Results** `${{ steps['snowCreate'].output.result }}`
