apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: snow-devhub
  title: Service Now dev hub
  description: Create a record in ServiceNow table
  tags:
    - snow
spec:
  owner: rhdh
  type: service

  parameters:
    - title: Provide Name Entry for snow table
      required:
        - snowName
      properties:
        snowName:
          title: Requester Name
          type: string
        snowDept:
          title: Requester Deptartment
          type: string
        snowRequest:
          title: Request
          type: string
  steps:
    - id: snowCreate
      name: Snow
      action: servicenow:now:table:createRecord
      input:
        tableName: u_rhdhsnowrhdhsnow
        requestBody: {
             u_namename: "${{ parameters.snowName }}",
             u_dept: "${{ parameters.snowDept }}",
             u_request: "${{ parameters.snowRequest }}",
             u_name: test
         }

  output:
    text:
    - title: More information
      content: |
        **Results** `${{ steps['snowCreate'].output.result }}` You Entered Name : "${{ parameters.snowName }}, ${{ parameters.snowDept }}, ${{ parameters.snowRequest }}"
